### ISSUE TITLE
长尾细粒度图像分类

### ISSUE THREAD

**Issue by chastloveRYU** [ylingfeng/DynamicMLP#1]
hello，这是一个非常棒的工作，我将该方法用在遥感图像分类上取得了非常好的结果。请问你们有没有考虑长尾分类问题，现有的方法似乎没有啥用，您有什么建议呢？

**Comment by ylingfeng** [comment]
我们在这个工作中没有针对长尾数据进行额外的算法操作，目的是为了与其他算法的公平对比。然而事实上，对于具有长尾性质的数据集，在我们的方法基础上添加长尾算法是可以有效提升性能的。
具体有效的长尾算法，您可以参考我们今年的FGVC SnakeCLEF2022 比赛中获得第二名的方法[worknote](http://ceur-ws.org/Vol-3180/paper-180.pdf)，我们改进了一种重加权的loss来处理长尾数据集，希望帮到您~
