### ISSUE TITLE
多GPU训练问题

### ISSUE THREAD

**Issue by buaa-luzhi** [ylingfeng/DynamicMLP#2]
测试了多GPU训练模型，迭代几次后loss为nan，
请问作者该代码能很好地支持多GPU训练吗？谢谢

**Comment by ylingfeng** [comment]
代码是支持多GPU训练的，文中的结果就是基于8卡TITAN XP的实验结果。代码是通过nn.DataParallel来实现多GPU的。
loss结果为nan的情况我们在实验中并没有遇到过，但是你可以尝试一下：1）调整一下训练的学习率或是loss权重 2）验证一下单卡是否报nan 3）修改并使用分布式多GPU训练，即nn.DistributedDataParallel。希望能帮到你~
