### ISSUE TITLE
关于图像和外部因素之间高位交互的问题

### ISSUE THREAD

**Issue by QGY9964** [ylingfeng/DynamicMLP#3]
您好，这是一份很有启发性的工作，但我有一定不太明白，基于concat的融合后，也可以在后续的卷积等操作中实现图像和外部因素特征之间的高维交互呀，本文中DynamicMLP实现高维交互的方式，与其有什么优势吗？

**Comment by ylingfeng** [comment]
谢谢！concat以及其他方法在融合的过程中，图像和地理特征的关系是对等的，没有考虑二者对结果的比重，而是全交由网络来学习。但是我们认为应当还是以图像特征为主导，只不过辅助以地理特征对其就行修正，所以就实现方法而言，我们是用地理特征作为基底对图像进行投影
